### ISSUE TITLE
Full repository data importing failed

### ISSUE THREAD

**Issue by jeroenschepens** [mantisbt-plugins/source-integration#117]
Repository data importing failed using generic git repository.
Tried with multiple repositories.
The error message only says: "Full repository data importing failed."

**Comment by jeroenschepens** [comment]
The repository is a local gitlab, the repo can be cloned without authentication.

**Comment by dregad** [comment]
@jeroenschepens I'm not sure what you mean by *generic git repository*. You should use the specific VCS plugin for the repository type you want to use, i.e. SourceGitlab in this case.
