### ISSUE TITLE
GIT repositories locally accessible by the GIT binaries

### ISSUE THREAD

**Issue by azabluda** [mantisbt-plugins/source-integration#119]
There doesn't seem to be an option to simply use local GIT binaries for integration. Are there any strong reasons against that?

**Comment by dregad** [comment]
None, except for the effort to develop the required plugin ;-)

**Comment by berarma** [comment]
+1 Parsing the git binaries output would be less prone to fail than parsing web interfaces. It could work with local and remote repositories. The only downfall is that local binaries must be available.

**Comment by dregad** [comment]
@berarma I will gladly merge such functionality, feel free to submit a pull request for review.
