### ISSUE TITLE
Pull request number in commit message mistaken with issue number

### ISSUE THREAD

**Issue by diegoqueiroz5a** [mantisbt-plugins/source-integration#120]
When merging a pull request, the plugin understands that the pull request number is an issue id, so it replaces the pull request number with the issue link.

Any thoughts on how to solve this?

**Comment by morgant** [comment]
There is a bit of unfortunate crossover between GitHub's parsing of `/#\d+/` as an Issue/Pull Request number and the this Source Integration plug-in also parsing the same as a Bug/Issue number. You could modify the Bug Link Regex Pass 1 & 2 and Bug Fixed Regex Pass 1 & 2 configuration values so they're more restrictive and won't match if preceded by "pull request" or "PR" (or whatever works best for your use cases).

**Comment by diegoqueiroz5a** [comment]
When changing the regex configuration, I have to update all the changesets again? Or just refresh the page?

**Comment by morgant** [comment]
It appears that the regular expressions are only used in `Source_Process_Changesets()`, which is only called during imports, so you'll need to re-import all your changesets again.
