### ISSUE TITLE
not working for bitbucket 

### ISSUE THREAD

**Issue by chintan9** [mantisbt-plugins/source-integration#125]
can i have detailed tutorials for installation?

**Comment by sverhagen** [comment]
Probably the answer is: *no, you can't*. Then, for the title of this issue: what is your problem with it?

**Comment by dregad** [comment]
> can i have detailed tutorials for installation? 

None exist that I know about. Maybe the plugin's author @lazar2606 is able to help.

If you get it to work and can compile your notes into a readme file, your contribution would bemore than welcome !
