### ISSUE TITLE
Cgit integration

### ISSUE THREAD

**Issue by nadirlc** [mantisbt-plugins/source-integration#126]
The changeset import works but the imported commit messages contain the string `<span class='decoration'></span>`. It seems this empty html tag is imported from cgit web interface. It would be nice to not show it in the commit messages in MantisBT

Thanks,
Nadir Latif

**Comment by nadirlc** [comment]
Usually Cgit repositories are password protected using Basic Authentication. The Cgit repository i am using is also protected by Basic Authentication. It would be useful to have support for Basic Authentication in the CGit plugin

Thanks,
Nadir Latif

**Comment by dregad** [comment]
Please open open distinct issues for each individual problem. You're also welcome to submit code contributions via pull request to fix those.

**Comment by nadirlc** [comment]
I would like to made a code contribution to fix my issues. can you describe the process of making the code contribution.

Thanks,
Nadir Latif

**Comment by dregad** [comment]
In short: fork the repo, create a branch for your fix, write and test your patch, push the branch with your commits to your github fork and submit a pull request. Refer to Github's help for further details.
