### ISSUE TITLE
Feature Request: Search - linked entries

### ISSUE THREAD

**Issue by Elompenta** [mantisbt-plugins/source-integration#128]
Add a Searchflag to find linked and not linked entires

**Comment by dregad** [comment]
By *linked entries*, you mean changesets that are attached to one or more issue(s) ? 

Can you please be more specific as to how you'd like this search to work ? Maybe a screen mock-up or a clear description would help.

**Comment by dregad** [comment]
@Elompenta your feedback on [my previous comment](https://github.com/mantisbt-plugins/source-integration/issues/128#issuecomment-281214645) would be appreciated.

**Comment by Elompenta** [comment]
@dregad Sorry, but i have no clue about this idea from 2015
I think you can Close this issue, and i will come back if it needed.

thanks

**Comment by dregad** [comment]
OK, thanks for the feedback
