### ISSUE TITLE
Error Importing SVN 

### ISSUE THREAD

**Issue by jangilla** [mantisbt-plugins/source-integration#132]
Since a few days I am getting the following error while importing SVN Repositories. Does anyone has a clue where the error comes from?

```
SYSTEM WARNING: 'SimpleXMLElement::__construct(): Entity: line 3: parser error : Premature end of data in tag info line 2' in '/var/www/vhosts/jangilla.de/httpdocs/dev_it-kl_eu/plugins/SourceSVN/SourceSVN.php' line 228

SYSTEM WARNING: 'SimpleXMLElement::__construct(): ' in '/var/www/vhosts/jangilla.de/httpdocs/dev_it-kl_eu/plugins/SourceSVN/SourceSVN.php' line 228

SYSTEM WARNING: 'SimpleXMLElement::__construct(): ^' in '/var/www/vhosts/jangilla.de/httpdocs/dev_it-kl_eu/plugins/SourceSVN/SourceSVN.php' line 228

svn info returned invalid xml code
```
MantisBT is running under Plesk 12.0.18 (Update 52, Debian 7.8) at the moment. The Plesk Server also offers the SVN Repository.

MantisBT-Version 	1.2.19

**Comment by dregad** [comment]
I don't use SVN myself so I can't say for sure, but looking at the plugin's code it would appear that the XML returned by `svn info <repo_url> --xml` is invalid. I would guess this is code by a change in your system (maybe a new SVN version, or a problem in executing the SVN command)

**Comment by jangilla** [comment]
Thanks for this information! I were able to fix the error...

https://serverfault.com/a/129135
