### ISSUE TITLE
GitWeb: unable to configure Basic Auth parameters

### ISSUE THREAD

**Issue by wuttke** [mantisbt-plugins/source-integration#143]
My GitWeb installation is protected by user name and password, but I am unable to configure this information with the SourceGitweb plugin.

**Comment by wuttke** [comment]
I've created a Pull request (can I link it somehow?) that implements this behaviour.

**Comment by dregad** [comment]
Fixed in 04b8a0a8cd4304102cb199790f4f1ed406e3d595
