### ISSUE TITLE
CGit: Database query failed when importing repository

### ISSUE THREAD

**Issue by davewood** [mantisbt-plugins/source-integration#149]
I am not sure whats wrong. When I click "Import everything i get this error msg"

My guess is that the git repo cannot be accessed but the documentation lacks information how to do so. Searching for "api key cgit" does not yield anything of help so I am not sure where things go wrong.

Does this plugin pull the information from cgit and authorizes with the api key? or is the api key for authorization for the curl call? Is the api key required for importing via the "Import Everything" button?

mantisbt 1.2.19
using the latest plugin from github/master
debian

```
APPLICATION ERROR #401

Database query failed. Error received from database was #1048: Column 'revision' cannot be null for the query: INSERT INTO mantis_plugin_Source_changeset_table ( repo_id, revision, parent, branch, user_id,
timestamp, author, message, info, ported, author_email, committer, committer_email, committer_id
) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? ).

Please use the "Back" button in your web browser to return to the previous page. There you can correct whatever problems were identified in this error or select another action. You can also click an option from the menu bar to go directly to a new section.
```

**Comment by dregad** [comment]
I don't use CGIT, so I'm not sure I can help. Maybe you can set `$g_show_detailed_errors = ON;` to try and understand where the problem occurs and debug from there.

**Comment by davewood** [comment]
Info for anyone else reading this issue and looking for details.

The problem is more then likely a firewall between cgit server and mantis server.

**Comment by dregad** [comment]
Is this resolved then ?

**Comment by davewood** [comment]
not really since I couldnt try this with properly configured firewall yet.

**Comment by dregad** [comment]
As you have not updated this for some months, I'm closing this issue. Feel free to update it if you can provide useful information to help diagnose or resolve the issue.

**Comment by dregad** [comment]
Reopening following submission of PR #377 (thanks @rick-gnous)
