### ISSUE TITLE
gitweb. Retrieving master ... commit data failure.int(0)

### ISSUE THREAD

**Issue by davewood** [mantisbt-plugins/source-integration#150]
latest plugin from github/master

mantisbt 1.2.19 (debian)

When I try to import everything I get this error msg.

```
Retrieving master ... commit data failure.int(0)
bool(false)
bool(false)
```

```
array(3) {
  ["gitweb_root"]=>
  string(45) "http://foobar.at/gitweb/"
  ["gitweb_project"]=>
  string(15) "Foobar.git"
  ["master_branch"]=>
  string(6) "master"
}
```

**Comment by dregad** [comment]
Looking at the code triggering this error, it would seem that the input received was invalid (length 0), so maybe the commit URL is invalid ? If I'm not mistaken, it should be like this: http://foobar.at/gitweb/?p=Foobar.git;a=commit;h=master

**Comment by davewood** [comment]
Hey dregad, thank you for your answer.

There is no example configuration so I cannot tell whether or not my config is correct or not.

One thing I just figured out is that I cannot access the server running gitweb, so that's my mistake. :)

Can you paste a working example gitweb config?

I'll add $g_show_detailed_errors = ON; and see if I get a better error msg.

**Comment by dregad** [comment]
> Can you provide a working example gitweb config?

I can't, sorry - I only use Github these days.

I think the key here is [the `url_get()` call](https://github.com/mantisbt-plugins/source-integration/blob/master/SourceGitweb/SourceGitweb.php#L228) which (apparently) returns an empty string for you. What is the value of `$t_commit_url` and `$t_input` after that call ? Also, how is  `url_get()` retrieving the URL ?

**Comment by davewood** [comment]
looks correct

$t_commit_url contains the string 'http://foobar.at/gitweb/?p=Foobar.git;a=commit;h=master';

**Comment by davewood** [comment]
it seems to boil down to this:

url_get($t_commit_url) is not allowed to access the $t_commit_url, but the error is not caught because url_get doesnt return false but an empty string.
https://github.com/mantisbt-plugins/source-integration/blob/master/SourceGitweb/SourceGitweb.php#L230

the error msg overall is not very helpful for an enduser
