### ISSUE TITLE
Gitlab commit branch detection not useful

### ISSUE THREAD

**Issue by hcw70** [mantisbt-plugins/source-integration#152]
While trying to implement git-flow in the plugin, i found out that the detection of the branch upon which a commit is based is not very useful.

A commit is reported on the branch if it is reachable from the commit labeled with the branch. 

It would be better if only the commits were reported on that branch which are on the tip of the branch.

See my efforts on: 

https://github.com/hcw70/source-integration/tree/feature/GitFlow_Adaptions

Merge request might follow if we can sort out the branch naming problem ... 8->

**Comment by hcw70** [comment]
At least this happens when doing a "Import Everything".

**Comment by dregad** [comment]
@hcw70 Your expectations are not really clear... Moreover, you mentioned you'd send a pull request but I never saw one coming, so I'm not what the status of this issue is. Can I close it ?

**Comment by hcw70** [comment]
My interest (last year) was to implement git-flow integration with this plugin. But this proved to be not feasible, so i moved on....

**Comment by dregad** [comment]
OK, thanks for the feedback.
