### ISSUE TITLE
Gitlab hook failed with code 403

### ISSUE THREAD

**Issue by zer0-x** [mantisbt-plugins/source-integration#153]
I added a web hook in GitLab but it fails to test every time and doesn't actually work when I commit.
It seems GitLab has been blocked by my Mantis instance.

I tried adding gitlab.com or it's IP 104.210.2.228 (IP from the ping command) but no effects too.
But everything works in web browser, I mean I can update the repo manually, or even using curl command with the same URL of GitLab hook.
More specifically about using curl, the import URL works but the check-in URL doesn't and its output contains "A required parameter to this page (data) was not found".

I'm using Mantis 1.2.19 with Source Control Integration 0.18 and GitLab Integration 1.0.3.
I think I configured it right and maybe this is a bug.

**Comment by dregad** [comment]
Is this still an issue ?

**Comment by zer0-x** [comment]
It has been too long for me to remember exactly, but I believe that if it worked I would have updated this issue.
