### ISSUE TITLE
Repo Importing ignored changes made in the last year

### ISSUE THREAD

**Issue by zer0-x** [mantisbt-plugins/source-integration#154]
Hi, I've run into a problem about importing.
When importing a big repository, the job is executing so long that a server will kill it (php timeout I guess).
My installation can't import the whole repo, it only updates under 50 most recent changesets then stops.
And import lastest data clearly doesn't help since the missing changesets was in the past. 
I've examined this carefully and I'm pretty sure this is caused by php timeout.
Unfortunately on a shared hosting (my case), I'm not able to edit it php configuration.

At first my hosting used Clouflare and the import job is killed by cloudflare's timeout.
So I try disabling CF, the imports runned longer a little bit and was killed by my own hosting then.

With CF it always update 44 latest changesets with the "Import Everything" option
Without CF timeout, it always update to 49 latest changesets with the "Import Everything" option.

I think I can rebuild my repo, re-push the commits and import incrementally by myself.
So I suggest we should have incremental importing if you still value the shared hosting users to import big repo.

**Comment by dregad** [comment]
All users are valued, shared hosting or not :wink: 

*Import latest* should work incrementally. I suggest you have a look at #60

**Comment by zer0-x** [comment]
Thanks for replying, I tried repeating "Import latest" only but it never get my oldest commits, my gitlab repo has 67 commits but the mantis repo only has 48 changesets (48 latest commits). I've been trying any options I can think of but can not see my the early commits.
Regarding #60, I think that's a workaround if SourceIntegrarion doesn't link the right issues, mine still hasn't had an issue yet.
Any ideas about what I can do next?
Thank you in advance.

**Comment by zer0-x** [comment]
Update: I notice that the missing commits are made in 2015.
@dregad The incremental importing works, but I think the year is the problems, it only fetch changes in current year :smiley: 
This is getting more interesting. Please fix soon if you can.

**Comment by dregad** [comment]
@zer0-x I'm sorry but I'm not able to reproduce the problem. In my tests, the plugin (eventually) successfully imports all commits including older ones. There is no filter by date.
