### ISSUE TITLE
Changesets garbled character

### ISSUE THREAD

**Issue by erhuabushuo** [mantisbt-plugins/source-integration#158]
It doesn't support chinese commited message.

æµè¯ä¸­æ

**Comment by erhuabushuo** [comment]
Repositories -> [ Changesets ]

**Comment by dregad** [comment]
There are some known issues with UTF8 support, see #156 

The information you provide is not sufficient to assess whether this is the same problem or not. Can you please be more specific as to where the problem occurs (maybe provide a screenshot). Check also in the database whether the data is stored properly and if not verify the table structure and encoding.

**Comment by dregad** [comment]
Without feedback from you, I'll close this issue. Feel free to reopen if needed.
