### ISSUE TITLE
unable to realise initial import after plugin installation

### ISSUE THREAD

**Issue by lracape** [mantisbt-plugins/source-integration#159]
Since many weekks I m trying to install this plugin to link my svn deliveries to my mantis issue. But after many different config I m unable to import my repository. Mysql database is empty ...
My config:
Mantis and svn are on the same https webserver.
Mantis : 1.2.19
subversion : 1.8.8
php : 5.6.12
apache : 2.4.18
https server / websvn

I have no error in the log messages. But when I try to import first time , I have the message "svn info return invalid xml code"
thanks for your help ....

**Comment by lracape** [comment]
function svn_check seems to be the source of the pb ...

**Comment by dregad** [comment]
I don't use SVN and the information provided is not enough to understand what is causing the issue. I'm closing this issue, feel free to reopen if you can provide a way to reproduce the problem.
