### ISSUE TITLE
Compatibility with MantisBT Core 1.3.0

### ISSUE THREAD

**Issue by Montikore** [mantisbt-plugins/source-integration#160]
Hi,

It seems the current version of this plugin does not support MantisBT Core 1.3.0. Is there any developments intended to make it compatible?
(i'm saying that because of our commit hook actions which are now failing with the new mantis core, and the warnings in the plugin management)

Thank you

**Comment by atrol** [comment]
Do you use branch master-1.3.x?

**Comment by Montikore** [comment]
ok i didn't see that... just tried and it works perfectly :)
sorry for this useless question and thanks for your help!

**Comment by vboctor** [comment]
I've just updated the readme file to clarify the version compatibility and corresponding branch for each supported version.
