### ISSUE TITLE
Not working with MantisBt 1.3.0

### ISSUE THREAD

**Issue by A016699** [mantisbt-plugins/source-integration#166]
Hi
 I'm just upgraded to mantins 1.3.0 - and tried to get thi splugin working.  As i copied all the plugisn i needed it tell me it can't be installed.
On Configuration page i see that the Dependencies are not are wrong. It shows me that I need MantisBT Core 1.2.0

What did I'm wrong ? Anyone can help me.
 
André

**Comment by atrol** [comment]
You have to use branch master-1.3.x of the plugin to use it with MantisBT 1.3.0.

**Comment by andersruneson** [comment]
It seems SourceWebSVN still depends on 1.2, is that a mistake?
https://github.com/mantisbt-plugins/source-integration/blob/master-1.3.x/SourceWebSVN/SourceWebSVN.php#L17

**Comment by dregad** [comment]
> It seems SourceWebSVN still depends on 1.2, is that a mistake?

Yes; it would appear that the 1.3.x branch was created, only a few selected specific plugins's dependencies were updated. Will fix.
