### ISSUE TITLE
Data Type mismatch on master-1.3.x

### ISSUE THREAD

**Issue by andersruneson** [mantisbt-plugins/source-integration#167]
I'm trying to upgrade to v1.3 of Mantis with Source plugins. 

So I have an installation with the Source plugins (and a lot of existing repositories) that I want to upgrade and here are my steps:
1. Installed mantisbt on a new server
2. Made a copy of the production database and using the copy for the new mantis installation
3. Installed plugins Source, SourceSVN and SourceWebSVN by copying them to the plugins-folder
4. When going to plugin.php?page=Source/manage_config_page I get this error:
APPLICATION ERROR #26, Data Type mismatch.

Is there a difference in the format for 1.2 and 1.3 of the Source plugin?
Where do I enable the detailed error messages?
What can I do to help?

**Comment by dregad** [comment]
Hello Anders

> Is there a difference in the format for 1.2 and 1.3 of the Source plugin?

No

> Where do I enable the detailed error messages?

In your Mantis config_inc.php, set `$g_show_detailed_errors = ON;`

That should give you the detailed stack trace, which will help understand what is causing the problem.

**Comment by andersruneson** [comment]
This only happens when the SourceSVN plugin is installed:

Full path: /var/www/mantis/core/helper_api.php
Line: 191
Variable	Value	Type
p_var1		string
p_var2	1	boolean
p_strict	1	boolean
Filename	Line			Function	Args
/var/www/mantis/core/helper_api.php	191	-	-	trigger_error	( <string>'26', <integer>256 )
/var/www/mantis/core/helper_api.php	240	-	-	helper_check_variables_equal	( <string>'', <boolean>true, <boolean>true )
/var/www/mantis/plugins/SourceSVN/SourceSVN.php	183	-	-	check_checked	( <string>'' )
/var/www/mantis/plugins/Source/Source.API.php	530	SourceSVNPlugin	->	update_config_form	-
/var/www/mantis/plugins/Source/pages/manage_config_page.php	319	SourceVCSWrapper	->	__call	( <string>'update_config_form', <array> { } )
/var/www/mantis/plugin.php	69	-	-	include	( <string>'/var/www/mantis/plugins/Source/pages/manage_config_page.php' )

**Comment by andersruneson** [comment]
Seems to work if I delete the config_id named plugin_SourceSVN_winstart in mantis_config_table.

**Comment by dregad** [comment]
Thanks for the update. I can reproduce the problem.

Mantis 1.3 changed the behavior of check_checked() function to perform strict comparison, so `'' === true` is causing the type mismatch.

**Comment by andersruneson** [comment]
Thanks for fast support! That fixed it.
