### ISSUE TITLE
Namespace is invalid

### ISSUE THREAD

**Issue by ModdyLP** [mantisbt-plugins/source-integration#169]
Hello

everytime when i add a Projekt, i get the error: "Repository Name is invalid". The Name is right and the namespace also. I had typed in "ModdyLP/AncientRegions".

**Comment by morgant** [comment]
@ModdyLP Am I correct in assuming this is a GitHub repo that you're trying to configure in the SourceGithub plugin?

**Comment by ModdyLP** [comment]
No it is a GitLab Repo, that i'am trying to import into the SourceGitLab pugin. I am using Mantis version 2.0.0 beta and SourceIntegration version 2.0.x

**Comment by dregad** [comment]
I do not use Gitlab, so I'm not sure I can help that much. 

Looking at the code, it seems this message is the result of receiving unexpected JSON while trying to determine the Gitlab project id. The plugin is retrieving it from `(hub_root)/api/v3/projects/(hub_reponame)`

- Check if the generated URL is correct. Maybe [dump the $t_uri variable here](https://github.com/mantisbt-plugins/source-integration/blob/master/SourceGitlab/SourceGitlab.php#L160).
- Try to call the webservice at that URL manually, see what you get

**Comment by dregad** [comment]
@ModdyLP you did not provide any feedback, so I'm closing this issue. Feel free to reopen if necessary.
