### ISSUE TITLE
have used gitlab. but gitlab's issues not import to mantisbt

### ISSUE THREAD

**Issue by taozywu** [mantisbt-plugins/source-integration#171]
Hi,all.

have used gitlab. but gitlab's issues not import to mantisbt? who can help me ?

GitLab Integration 1.0.3：MantisBT Core 1.2.0 & Source Control Integration 0.16

SourceGitlab.php in Attach file.

[SourceGitlab.zip](https://github.com/mantisbt-plugins/source-integration/files/433989/SourceGitlab.zip)

**Comment by taozywu** [comment]
i found this link 

> http://stackoverflow.com/questions/37705817/what-may-be-the-issue-for-the-files-and-issues-not-getting-updated-in-the-mantis

but no found resolved.  who can help me ?

**Comment by dregad** [comment]
@taozywu what you are trying to do and the problem you are facing is really not clear. The SO issue you refer to is equally unclear, probably also the reason it was not answered.

Disclaimer: I did not write and do not use the Gitlab plugin, so I'm not sure I would be able to help, but for sure the information provided is not sufficient.

**Comment by taozywu** [comment]
thank you @dregad .

my question as follow：

> Using Gitlab integrated with Mantis BT Mantis BT -> Repositories -> Manage, when clicked on import the latest data, data is getting imported and the changesets value is getting updated but the statistics files and issues values are not getting updated

Issues: What may be the issue for the values not getting updated? Does it require any change in MantisSourcePlugin code?

**Comment by dregad** [comment]
Copy/pasting the text really does not help. See comment by libregeek.

**Comment by taozywu** [comment]
Okay, Thanks anyway!
