### ISSUE TITLE
Websvn add or edit repository graphical issues

### ISSUE THREAD

**Issue by andersruneson** [mantisbt-plugins/source-integration#174]
When using mantisbt 1.3.1 with websvn source integration I found a graphical issue when adding or editing a repository:
![websvnsourceintegration](https://cloud.githubusercontent.com/assets/1451776/18286101/9e40bbce-7471-11e6-80ac-724ca15239a2.png)

**Comment by bdrajer** [comment]
A similar thing happens for HG. It seems that the misplaced fields should be wrapped in <div class="field-container"> like the other ones.

**Comment by dregad** [comment]
Sounds like a consequence of the changes in the way Mantis handles the page layout in 1.3.

Pull requests are welcome.

**Comment by evilchewits** [comment]
Could you please review this fix.
