### ISSUE TITLE
style.css loaded as text/html causing console error

### ISSUE THREAD

**Issue by vboctor** [mantisbt-plugins/source-integration#178]
Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://localhost/mantisbt/plugin_file.php?file=Source/style.css".

This was reproduced on modern-ui branch.  Didn't test on classic ui branch.

**Comment by dregad** [comment]
@vboctor Mime type looks OK to me https://github.com/mantisbt-plugins/source-integration/blob/master/Source/Source.php#L136

Where do you see the error ?
