### ISSUE TITLE
Source control user preference UI broken for modern UI

### ISSUE THREAD

**Issue by vboctor** [mantisbt-plugins/source-integration#180]
![user_pref_for_source_control_username](https://cloud.githubusercontent.com/assets/6446/20592003/4e5501ea-b1e0-11e6-8478-23adae7f84c6.png)

**Comment by CrazyLinuxNerd** [comment]
Hi,

I noticed this myself today also as I just converted our local bugtracker to MantisBT v2.0-rc1.

I decided to look into this bug as it was bugging me.

Found a fix quite quickly:

Open Source/SourceIntegration.php and find (around line 86-91):
>		echo '<div class="field-container">'
>			. '<label for="Source_vcs_username"><span>' . plugin_lang_get( 'vcs_username', 'Source' ) . '</span></label>'
>			. '<span class="input"><input type="hidden" name="Source_vcs" value="1"/>'
>			. '<input name="Source_vcs_username" value="', $t_user->username, '"/></span>'
>			. '<span class="label-style"></span>'
>			. '</div>';

Replace with:
>		echo '<tr>'
>			. '<td class="category">' . plugin_lang_get( 'vcs_username', 'Source' ) . '</td>'
>			. '<td>'
>			. '<input type="hidden" name="Source_vcs" value="1"/>'
>			. '<input name="Source_vcs_username" value="' . $t_user->username . '"/>'
>			. '</td>'
>			. '</tr>';

This worked for me and the field shows up correctly now :-).

Hope this helps!

**Comment by CrazyLinuxNerd** [comment]
Hi,

I noticed this myself today also as I just converted our local bugtracker to MantisBT v2.0-rc1.

I decided to look into this bug as it was bugging me.

Found a fix quite quickly:

Open Source/SourceIntegration.php and find (around line 86-91):
>		echo '<div class="field-container">'
>			. '<label for="Source_vcs_username"><span>' . plugin_lang_get( 'vcs_username', 'Source' ) . '</span></label>'
>			. '<span class="input"><input type="hidden" name="Source_vcs" value="1"/>'
>			. '<input name="Source_vcs_username" value="', $t_user->username, '"/></span>'
>			. '<span class="label-style"></span>'
>			. '</div>';

Replace with:
>		echo '<tr>'
>			. '<td class="category">' . plugin_lang_get( 'vcs_username', 'Source' ) . '</td>'
>			. '<td>'
>			. '<input type="hidden" name="Source_vcs" value="1"/>'
>			. '<input id="source-vcs-username" type="text" name="Source_vcs_username" class="input-sm" value="' . $t_user->username . '" />'
>			. '</td>'
>			. '</tr>';

This worked for me and the field shows up correctly now :).

Hope this helps!

Note: Repost because my first version was slightly incorrect it turns out, but this one is 100% correct.. I think :D

**Comment by vboctor** [comment]
@CrazyLinuxNerd Would you be able to post a pull request for this fix?

**Comment by CrazyLinuxNerd** [comment]
Done :-)

**Comment by dregad** [comment]
Fixed in feb5388a731596448fb18aa06be997381c547e44, thanks @CrazyLinuxNerd
