### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by muranyia** [mantisbt-plugins/source-integration#181]
When installing into MantisBT 1.3.3 the following error appears:
```
APPLICATION ERROR #2503
Upgrading the plugin schema failed in block #0.
```
The plugin is installed, in the Installed Plugins table the Dependencies item is orange and an [Upgrade] link is displayed. Clicking on Upgrade results in the same error.

**Comment by dregad** [comment]
I'm not able to replicate this.

Is this a fresh install or an upgrade ? What DB ? Does the DB user have enough privileges to create and alter tables and indexes ?

**Comment by muranyia** [comment]
This is a fresh install on MariaDB. The MantisBT user hasSELECT, INSERT, UPDATE, and DELETE privileges only as prescribed in [the MantisBT Manual](https://www.mantisbt.org/docs/master-1.3.x/en-US/Admin_Guide/html-desktop/#admin.install.requirements)

**Comment by dregad** [comment]
This is a known issue with mantisbt core plugin api, see http://www.mantisbt.org/bugs/view.php?id=13137

I suggest you temporarily increase your mantis user's privileges to install the plugin.
