### ISSUE TITLE
Non ASCII chars are stripped from password

### ISSUE THREAD

**Issue by ThomasTr** [mantisbt-plugins/source-integration#187]
Due to escapeshellarg($p_repo->info['svn_password']); in SourceSVN.php at line 339, non ASCII chars are stripped from password.

**Comment by dregad** [comment]
@ThomasTr can you please be more specific ? I'm trying to replicate the problem but it seems to work just fine for me.

Maybe it's specific to your environment. Can you check if your locale settings are correct ? See https://bugs.php.net/bug.php?id=54391, http://php.net/manual/en/function.escapeshellarg.php#88325

**Comment by dregad** [comment]
Since you did not provide any feedback, I'm closing this issue. Feel free to reopen with additional information.
