### ISSUE TITLE
Request (proposal): Adding default event triggers for bug updates

### ISSUE THREAD

**Issue by cdevroe** [mantisbt-plugins/source-integration#189]
Hi all,

Forgive the newb question/proposal. We're new to Mantis and are using this plugin to connect to Gitlab to keep our bug tracker up-to-date with source commits using the "fixed" and "issue" commit message tracking. Works a charm, well done to all for this!

However, we also have a plugin that updates the appropriate Slack channels with a ticket is closed or resolved. However, the Source Integration plugin does not trigger the appropriate Mantis events - which I believe it should anyway, right? - to end up triggering the other Slack plugin.

I searched the issues and have not found a discussion around this. Is this something that was omitted on purpose or has no one else run into this?

I was thinking this could be added to the API right around here: https://github.com/mantisbt-plugins/source-integration/blob/master/Source/Source.API.php#L392

We could add something like:
`event_signal( 'EVENT_UPDATE_BUG' )`

(or any other triggers that seem appropriate at this point).

Does anyone have an opinion? Are we barking up the wrong tree? Thanks in advance for any input.

**Comment by dregad** [comment]
With regards to triggering the bug update event, it should technically be done by the MantisBT core [here](https://github.com/mantisbt-plugins/source-integration/blob/master/Source/Source.API.php#L382).

Suggest you have a look at [#20577](http://www.mantisbt.org/bugs/view.php?id=20577), this sounds like the same issue.

**Comment by dregad** [comment]
I take the thumbs up you gave to my earlier comment as an agreement that this is not something that should be handled by the source integration plugin. Consequently, I'll close this issue, feel free to reopen if my understanding is incorrect.
