### ISSUE TITLE
Accept branches containing slash '/' character

### ISSUE THREAD

**Issue by timosmit** [mantisbt-plugins/source-integration#193]
I have several development branches (dev/1.1.0, dev/1.2.0, etc) which I would like to add to my tracking as well. The thing is, when adding these, the plugin aborts with the error that there is an invalid character in my branch list (supposedly the '/' char).

I'm currently testing a small patch of `source-integration/SourceGithub/SourceGithub.php` in which the regex on line 211 accepts the slash character. Currently I have not experienced any issues with other parts of the plug-in; if this stays the same, I will submit a PR.

On a sidenote, escaping the dot '.' character in a character class should not be necessary (this relates to the same regex).

**Comment by dregad** [comment]
The same issue probably applies to other git-based repos (GitLab, Bitbucket...)

**Comment by dregad** [comment]
After a bit of research on what the [allowed chars in a git branch name](https://www.kernel.org/pub/software/scm/git/docs/git-check-ref-format.html) are, I would propose the following regex to replace the current one:

```
%^(?!/|.*([/.]\.|//|@\{|\\)|@$)[^\000-\037\177 ~^:?*[]+(?<!\.lock|[/.])$%
```

I have not fully tested it, but it covers your '/' case (and more) as far as I can tell. Let me know if that works for you.

**Comment by timosmit** [comment]
I think the issue is more complicated than just the regex. As can be seen on my [bugtracker](http://dev.timosmit.com/bugtracker/plugin.php?page=Source/list&id=2), it somehow truncates the nested branch part (instead of *develop/1.2.0* only *develop* is shown as branch name). However this used to be no issue, since some commits were correctly listed in *develop/1.2.0* as can be seen [here](http://dev.timosmit.com/bugtracker/plugin.php?page=Source/view&id=111).

**Comment by dregad** [comment]
OK I managed to reproduce the problem.

Indeed, changesets that are imported in bulk via the *Import everything* button are properly assigned to the branch. The problem only occurs when processing the payload sent by the Github webhook.

Looking at the git history, I believe this was introduced by 749797b928c9b9048fc1d2dd5bf9154db134cd30; Github sends a full reference to the branch, e.g. `ref/heads/xxxx`. The use of *explode()* (as replacement for originally used, deprecated split()*) does not take branches containing one or more `/` (like your*dev/1.1.0* example) into consideration.

I'll submit a pull request shortly.
