### ISSUE TITLE
Searching through the changeset repository could show which commits are already linked to tickets 

### ISSUE THREAD

**Issue by luzpaz** [mantisbt-plugins/source-integration#202]
Scenario: A project is migrating from python2 to python3 and you can imagine it's a ton of commits. Some of the devs are not associating their commits to the designated ticket. So in order to organize and associate all the py3 commits they need to be searched by keywords. Say that be 'py3' so using the search function brings up all commits with py3 in them. Now some of the commits have been associated already with the ticket... but I can't tell which one since the UI doesn't indicate that. So I need to open each an everyone individually in order to ascertain if it's been attached. 

Solution: commits that are attached to a ticket can be designated with a certain color or mention highlight the ticket they are attached to somewhere within the search results.

Related to #128 

Edit:
Mind you this is also an issue say if not all the commits have the same identifying keyword. Instead of 'py3' what if the commit message has 'python3' in it or 'python 3'. Some of the commits will have multiple keywords..so the results will overlap. Again, there is no way to see what commits have been attached so one needs to open each and everyone of them.

**Comment by luzpaz** [comment]
Possible location of where it's possible to indicate in the UI if the ticket is attached to a ticket and the ticket/s number:

![attached-location](https://cloud.githubusercontent.com/assets/4140247/23862218/cf2ff65a-07e2-11e7-93c3-31d00d014f17.png)

**Comment by luzpaz** [comment]
In addition to the above... would it be possible to add an attach ticket field? see mockup:
![source-integration-attach-box](https://cloud.githubusercontent.com/assets/4140247/24112918/7145ca6c-0d71-11e7-8538-33ea76ea7cb3.jpg)

**Comment by dregad** [comment]
See #224 for proposed implementation

**Comment by luzpaz** [comment]
@dregad thanks for working on this! I've been assured this PR looks good. Looking forward to he next release!
