### ISSUE TITLE
Souce-integration doesn't respect GitHub PR commit message revisisions via GitHub UI

### ISSUE THREAD

**Issue by luzpaz** [mantisbt-plugins/source-integration#208]
I'm assuming (haven't deduced this from the code but from behaviour) that when a git commit or PR is made to GitHub that MantisBT registers that. 

Say a scenario, the PR submitter didn't formulate the commit correctly with the correct Source-Integration regex, which won't trigger Mantis to link the changeset to the appropriate ticket. So if one wants to correct the PR commit message for this to happen (without re-pushing the commit) through the Github UI by simply re-editing the git commit, Mantis won't register the change made after-the-fact. It will still register the message that was first committed without revisions. 

Example: 
* Changeset: https://freecadweb.org/tracker/plugin.php?page=Source/view&id=7012 
![image](https://cloud.githubusercontent.com/assets/4140247/24048923/cb39fb9c-0b00-11e7-92bf-bb214667c3fe.png)
-----
* PR request: https://github.com/FreeCAD/FreeCAD/pull/612
![image](https://cloud.githubusercontent.com/assets/4140247/24049015/16ec5fee-0b01-11e7-8337-4a5568c51334.png)
------
* Commit: https://github.com/FreeCAD/FreeCAD/commit/2dc12cd5416830ee67c2aba362d8285acadfb26f
![image](https://cloud.githubusercontent.com/assets/4140247/24049072/423bcf36-0b01-11e7-9e6f-09872e500969.png)

**Comment by luzpaz** [comment]
Sorry, I just noticed that this may not be a MantisBT issue. I was looking at  FreeCAD/FreeCAD@2dc12cd and realized @yorikvanhavre committed the original commit message and not the revised one.

**Comment by dregad** [comment]
> if one wants to correct the PR commit message 

You can't do that in GIT without rewriting the history, which is something you should in principle never do.

The only thing you can do is manually change the bug assignments in Mantis after the fact (as per our earlier discussions on the subject).

**Comment by dregad** [comment]
>  committed the original commit message and not the revised one.

Do not confuse the Github pull request description text, with the commit message, they are 2 distinct things; the only relationship is that when the PR is opened for a branch that has just 1 commit, then its title and description will be a copy of the commit message
