### ISSUE TITLE
Ease of access to search git commit by revision number

### ISSUE THREAD

**Issue by luzpaz** [mantisbt-plugins/source-integration#209]
Currently, this is the workflow that is needed to get to the source-integration search menu:
* click Repositories side menu flyout menu
* click the the `search` button
* find the Revision field and enter the revision number

Instead could we consider adding a search box to one of the following places? 
![source-integration-search-box](https://cloud.githubusercontent.com/assets/4140247/24112197/280971ca-0d6f-11e7-9650-1d9d4fb75d03.jpg)

**Comment by dregad** [comment]
To my knowledge, the ACE template does not allow adding widgets such as a search field to a menu item - maybe @syncguru can confirm that.

MantisBT does not offer a way for plugins to customize the NavBar either.

So your 2 suggestions are currently not feasible. As alternatives, we could add a new menu item to provide direct access to the search page.

Maybe an [OpenSearch](http://www.opensearch.org/) plugin could be an option too, but this is a different approach / use-case.

**Comment by luzpaz** [comment]
Bump @syncguru
