### ISSUE TITLE
Option to list changeset also by the dates commits were merged

### ISSUE THREAD

**Issue by luzpaz** [mantisbt-plugins/source-integration#210]
Currently Changesets are displayed by the dates they were committed. This creates a phenomena when PRs are submitted and sit in the queue for a while and then get merged. The date they were committed is how they will be displayed in the changeset. 

See attached example: 
![screenie](https://cloud.githubusercontent.com/assets/4140247/24164378/dc817542-0e43-11e7-8c1f-1edfb70a3a11.jpg)

Please offer the option to display the changeset as when specific commits were merged.

**Comment by dregad** [comment]
This is currently not feasible technically, because internally only a single timestamp is stored.
