### ISSUE TITLE
Missing requirement for SourceGithub plugin

### ISSUE THREAD

**Issue by boisei0** [mantisbt-plugins/source-integration#214]
On a php installation without curl support and where system calls are disabled, the server side authorising of the OAuth request will fail. See https://github.com/mantisbt-plugins/source-integration/blob/master/SourceGithub/SourceGithub.php#L501 for the relevant lines. Both options (curl and shell_exec) for sending a request will fail, and a message will be displayed to the client mentioning the authorisation has failed.

The requirements in the Mantis administration guide mention that Curl is optional (http://www.mantisbt.org/docs/master/en-US/Admin_Guide/html-desktop/#admin.install.requirements.software), and the installation instructions in the README for this repository only list Mantis 2.0.0 or higher as requirement. However, it should include curl as well.

**Comment by dregad** [comment]
Thanks for the heads up
