### ISSUE TITLE
String "plugin_SourceIntegration_affected_issues" not found

### ISSUE THREAD

**Issue by jensberke** [mantisbt-plugins/source-integration#231]
Hi,

the following warning message appears in the "Related Changesets" list for each change set:

```
APPLICATION WARNING #300: String "plugin_SourceIntegration_affected_issues" not found. (in 
'PATH_TO_MANTIS/core/lang_api.php' line 305)
```

Strangely, all other strings from the plugin are displayed correctly.

If I change the key `plugin_Source_affected_issues` to `plugin_SourceIntegration_affected_issues` in `Source/lang/strings_english.txt` the text is displayed correctly. 

Mantis 2.5.0
Source Integration 2.0.3 (also happens in current `master`)

Regards
Jens

**Comment by dregad** [comment]
Thanks for the bug report. Bug is confirmed as per screenshot below (regression from 5aec11023a9c242a67f2255e24b4377d28c6a4f4)

![screenshot-20170914-1611](https://user-images.githubusercontent.com/449891/30434585-f500f368-9967-11e7-9812-89af6ffba576.png)
