### ISSUE TITLE
GitPhp URL parameter seems useless (but could be useful)

### ISSUE THREAD

**Issue by mljrg** [mantisbt-plugins/source-integration#232]
I have configured GitPhP like this:

Name: Testes - master
Type: Gitphp
URL:
gitphp_root: http://localhost/gitphp
gitphp_project: repo.git
master_branch: master

This configuration allows me to load the changesets, but when jumping to their details MantisBT is using the "gitphp_root" parameter to build the URL to jump to, which does not work when using a browser in another computer.

I tried to configure URL with an https://<public domain>/gitphp, but MantisBT insists on using "gitphp_root".

Is it possible to give some useful use to the "URL" parameter, so that it is possible to have an internal address to load changesets from a local repo more efficiently via "gitphp_root", and use "URL" for jumps into the GitPhp site?

Thanks

**Comment by dregad** [comment]
The gitphp plug-in is a contribution from the community. I don't use it myself, and have no objection in enhancing it as per your suggestion. Feel free to submit a pull request.

**Comment by dregad** [comment]
Closing this for now. Again, a Pull request with proposed enhancement would be welcome.
