### ISSUE TITLE
Gogs support

### ISSUE THREAD

**Issue by Candesco** [mantisbt-plugins/source-integration#235]
Would it be possible to support Gogs (a self-hosted Git service, see [gogs.io](https://gogs.io/))?
It is very similar to GitHub and I think it might just be changing the GitHub-Plugin to allow a custom base URL instead of github.com.

**Comment by dregad** [comment]
You're welcome to contribute a new VCS plugin to support it.

**Comment by Candesco** [comment]
Thank you for the quick response. I've tried to implement something, but at this time Gogs doesn't fully support the necessary API features.
I'll try to keep my eyes on it and come back to it later.

**Comment by dregad** [comment]
OK, thanks for the feedback. I'll close this for now, feel free to reopen at a later time.
