### ISSUE TITLE
Question: Hide menu item Repositories for anonymous user

### ISSUE THREAD

**Issue by pedwik** [mantisbt-plugins/source-integration#240]
Is it possible to hide the Repositories item from the main menu for anonymous users?

**Comment by atrol** [comment]
Should work, asssuming you did not change access level for anonymous users:

- goto page Manage > Manage Plugins
- click on link `Source Control Integration 2.0.2`
- set `View Threshold` to `reporter`

**Comment by pedwik** [comment]
Works fine, selected View Threshold to developer, thank you.
