### ISSUE TITLE
How to import range of revisions?

### ISSUE THREAD

**Issue by pedwik** [mantisbt-plugins/source-integration#253]
When importing a ViewVC repository, you can select either to "Import Latest" (whatever that means) or "Import Everything". Neither works for me (Windows Server 2016). Can you select a specific range of revisions to import instead?

**Comment by dregad** [comment]
With regards to the difference between the two _Import_ buttons:
- _Import latest_ will process the changesets for an existing repository, starting from the tip of the branch(es) and importing changesets going backwards in time, whereas
- _Import everything_ will start from scratch, i.e. create a new, empty repo and import all changesets into it (following the same process)
 
There is currently no way to specify a range of revisions to import, for ViewVC or other plugins, sorry.

**Comment by dregad** [comment]
Closing this since you did not provide any further feedback.
