### ISSUE TITLE
Source with gitea?

### ISSUE THREAD

**Issue by gh-ghost** [mantisbt-plugins/source-integration#255]
Hi:

Because I use gitea for git repository,
I would like to know if you willing support a SourceGitea plugin?

Thank you

**Comment by dregad** [comment]
I will gladly add it to the repository if you provide a pull request with the plugin's source.

**Comment by dregad** [comment]
Closing the issue for now. As mentioned in my earlier post, please provide a pull request for this new integration whenever you're ready.

**Comment by dregad** [comment]
See PR #413
