### ISSUE TITLE
taking features from #114 in default branch?

### ISSUE THREAD

**Issue by Heavenfighter** [mantisbt-plugins/source-integration#258]
Hello,

i'm using this plugin over years and would be glad, if the features from pull request #114 were taking into default branch. The default branch gets update, but the fork doesnt.
Is there a possibility to merge the fork?

The features from the fork work reliable in combination with hg.

**Comment by dregad** [comment]
Sorry, I that's just me being busy and not having the time to review and integrate the pull request.

I'll close this issue as it does not add any value, please follow-up directly in #114 as needed.
