### ISSUE TITLE
Re-create database tables

### ISSUE THREAD

**Issue by Heideachim** [mantisbt-plugins/source-integration#260]
I have manually, deliberately, willfully, deleted the plugin_source_...-tables inside the mantisbt database. Is there a way to force source-integration to create them again, like it is done at first setup??

**Comment by dregad** [comment]
Open mantisbt manage configuration page and delete entries named `plugin_Source*_schema`

**Comment by Heideachim** [comment]
Works!
The mentioned entries are here: Manage -> Manage Configuration -> Configuration Report
