### ISSUE TITLE
Changesets imported no attached issues

### ISSUE THREAD

**Issue by tanasi** [mantisbt-plugins/source-integration#262]
Hi, 

at first thanks for this great addon. I have used that in the past (not installed/configured by me) so I know how powerful it is. So now I am trying to configure it for my own mantisbt. 

At the moment I have followed the instructions and seems that I am partially successful. I can commit a change to my SVN and then if I check in Mantis I can see in repositories>Changesets details regarding that commit. 
The issue is that navigating to a specific issue e.g. 0000003 I can not see any relevant info. I have performed the following steps:
- Installed Mantis, Subversion and Source integration Plugin in my VPS server
- Configured Source integration plugin and added the repository which resides in Assembla
- Created an API key and added that in configuration
- In Assembla and specific repository I added the following URL to run after every commit http://host.domain.tld/mantisbt/plugin.php?page=Source/import&id=all&api_key=<YOUR_API_KEY> 
 - I perform a change and then when commiting I use e.g. issue 3: Bla bla bla
- Checking Repositories>Changesets shows all the changed files
- There is no relevant info in issue with number ID =3. 

Any ideas? Do I need to install Websvn? Do i need the meta plugin? 
Thanks

**Comment by dregad** [comment]
@tanasi the automatic linking of changesets to issues is driven by the _Bug Link Regex Pass 1&2 settings in the plugin's configuration. Assuming you have not changed the default settings (`/(?:bugs?|issues?|reports?)+\s*:?\s+(?:#(?:\d+)[,\.\s]*)+/i`), you need to prefix the issue ID with `#`.

**Comment by tanasi** [comment]
You are absolutely right.. :+1: 
Adding the "#" did the trick!

Thanks for the support
