### ISSUE TITLE
gitlab no longer supports api/v3

### ISSUE THREAD

**Issue by commonhuman** [mantisbt-plugins/source-integration#272]
[API v3 was removed in GitLab 11.0.](https://docs.gitlab.com/ee/api/v3_to_v4.html)

just swap v3 for v4 in `api_uri( $p_repo, $p_path )` and your good to go

**Comment by dregad** [comment]
Err... #270 / 772b8040807e2220543c3e1e9010f60f67aa44ec  :roll_eyes:
