### ISSUE TITLE
SourceHgWeb metadata pattern does not work with PHP 5.5.9

### ISSUE THREAD

**Issue by epaul13** [mantisbt-plugins/source-integration#275]
I had to patch `SourceHgWeb.php` to make Mantis / Hgweb integration to work. It seems that my php version does not like the metadata pattern.

In function `commit_changeset`, I had to replace:

``` php
$s_pattern_metadata = '/^# (?:'
                . self::PATTERN_USER . '|'
                . self::PATTERN_DATE . '|'
                . self::PATTERN_REVISION
                . ')/J';
```

with

``` php
$s_pattern_metadata = '/^# (?J)(?:'
                . self::PATTERN_USER . '|'
                . self::PATTERN_DATE . '|'
                . self::PATTERN_REVISION
                . ')';
```
to make it work.

Source/SourceHgWeb version 2.1.2:

``` php
class SourceHgWebPlugin extends MantisSourcePlugin {
    const PLUGIN_VERSION = '2.1.2';
    /* ... */

```
PHP version 5.5.9:

``` sh
$ php --version
PHP 5.5.9-1ubuntu4.25 (cli) (built: May 10 2018 14:37:18) 
```

**Comment by dregad** [comment]
I can reproduce the problem with the pattern on CLI (PHP 5.5.9-1ubuntu4.20): _Warning: preg_match(): Unknown modifier 'J' in php shell code on line 1_

According to [documentation](http://php.net/manual/en/reference.pcre.pattern.modifiers.php), `J` as modifier is only supported as of PHP 7.2 (see under PCRE_INFO_JCHANGED), so I think your fix is correct.
