### ISSUE TITLE
SourceGitweb: import is highly dependend on gitweb version

### ISSUE THREAD

**Issue by hakankpunkt** [mantisbt-plugins/source-integration#28]
The various regexp for importing the change sets via SourceGitweb should be depended on the version of gitweb used. This would save a lot of adjustments.

**Comment by dregad** [comment]
Considering that this issue is nearly 5 years old, the fact that the description is quite vague and I don't know what to do with it since I don't use Gitweb myself, I'll close it for now. Feel free to reopen if needed, providing details on how the regex should be changed based on Gitweb version.
