### ISSUE TITLE
Post-commit with checkin.php or import.php?

### ISSUE THREAD

**Issue by pedwik** [mantisbt-plugins/source-integration#289]
After submitting a changeset to our SVN repo, a post-commit will be added to that the Mantis is also updated.  What is the difference between checkin.php and import.php? 

Setup: 
MantisBT 2.19,
Source Control Integration 2.1.5
Windows IIS 10

**Comment by dregad** [comment]
import.php is triggered manually, its purpose is to initialize the repository on the MantisBT side.
checkin.php meant to be called via a hook on from the version control system, so that the plugin's data is automatically kept up to date.
