### ISSUE TITLE
Subversion: "php-cgi -f plugin.php page=Source/import" hangs forever

### ISSUE THREAD

**Issue by palevi67** [mantisbt-plugins/source-integration#291]
Centos7, svn 1.7.14

I have been debuging for a while, and after changing line 327 in SourceSVN.php to:

      array( array( 'pipe', 'r' ), array( 'pipe', 'w' ), array( 'pipe', 'a' ) ),

(changed mode in stderr from **w** to **a**):

seems to be working ...

P.

**Comment by dregad** [comment]
This seems to be a duplicate of #259
