### ISSUE TITLE
User cannot view section "Related changesets"

### ISSUE THREAD

**Issue by pedwik** [mantisbt-plugins/source-integration#294]
We are two admin users of a Mantis site (version 2.19, using Source Control Integration v 2.1.5). In the view.php?id=... page, I can see the sections "Related Changesets" and "Issues History", but he cannot. We cannot find any information on why these sections are hidden for him. Any ideas?

**Comment by dregad** [comment]
I didn't test such a configuration to confirm if this is true, but my guess would be that your colleague has some project-specific access levels lower than Administrator.

In any case, considering that the problem also affects a core MantisBT feature (issue history), I doubt that this is related to the Source Integration plugin.

**Comment by pedwik** [comment]
He is definitely Administrator. So then I will post this issues elsewhere.
