### ISSUE TITLE
Improve GitHub documentation

### ISSUE THREAD

**Issue by dregad** [mantisbt-plugins/source-integration#304]
The [current documentation](https://github.com/mantisbt-plugins/source-integration/blob/v2.1.5/docs/CONFIGURING.SourceGithub.md) has not been revised since its creation back in 2016.

Moreover, it does not provide any instructions on how to automate the processing of commits as they are pushed to GitHub (previously with Services, and now with Webhooks).

**Comment by morgant** [comment]
@dregad Good point, I was actually using a cron job to run the update periodically. Thanks for all your work on these updates!

**Comment by dregad** [comment]
@morgant would you kindly review the updated doc and test the new Github integration functionality in https://github.com/dregad/source-integration/tree/gh-doc ? Let me know your thoughts
