### ISSUE TITLE
Checkin of same revision number from different repositories not possible

### ISSUE THREAD

**Issue by iflow** [mantisbt-plugins/source-integration#307]
Checkin of same revision number from different repositories not possible.

My situation: I have a setup with different repository directories:
- Repo A (http://domain.tld/svn/repo_a)
- Repo B (http://domain.tld/svn/repo_b)

My understandig was based on the documentation to create two projects in the mantis source plugin management:
- Name: _Repo A_ / Typ: _SVN_ / URL: _http://domain.tld/svn/repo_a_
- Name: _Repo B_ / Typ: _SVN_ / URL: _http://domain.tld/svn/repo_b_

1. If I do my first commit to Repo A, then I get the revision number 1.
2. Now import the revision into Mantis: https://domain.tld/mantis/plugin.php?page=Source/checkin&api_key=1234&data=1
3. The commit successfully appears in Mantis
4. If I do my first commit to Repo B, then I get also the revision number 1.
5. Now import the revision into Mantis: https://domain.tld/mantis/plugin.php?page=Source/checkin&api_key=1234&data=1
6. **Error: Revision 1 already committed!**

Is this a bug or configuration problem?

**Comment by obmsch** [comment]
@iflow At least param `repo_name` is missing from your calls.

`&api_key=1234&repo_name=RepoA&data=1` and `&api_key=1234&repo_name=RepoB&data=1`

should work.

**Comment by iflow** [comment]
Thank you! This does the trick. I added the parameter _repo_name_ to my CURL requests. Now the commits are correctly imported into Mantis.

The setup instructions may should be extended with possible parameters.

**Comment by iflow** [comment]
Thank you! This does the trick. I added the parameter _repo_name_ to my CURL requests. Now the commits are correctly imported into Mantis.

The setup instructions may should be extended with possible parameters.
