### ISSUE TITLE
How to configure SVN server hooks when repository contains multiple projects

### ISSUE THREAD

**Issue by DavidHopkinsFbr** [mantisbt-plugins/source-integration#310]
The SourceSVN code folder contains template files for [post-commit](https://github.com/mantisbt-plugins/source-integration/blob/master/SourceSVN/post-commit.tmpl) and [post-revprop-change](https://github.com/mantisbt-plugins/source-integration/blob/master/SourceSVN/post-revprop-change.tmpl) hooks, to allow the SVN server to notify the source integration plugin of changes.

I have a couple of questions:

1. The installation instructions don't mention setting up server-side hooks, only Mantis-side cron jobs to update on a schedule. Are hook-driven notifications deprecated, or just undocumented?
2. The cURL post to the source-integration API supplies a `PROJECT` parameter. Looking at [the code](https://github.com/mantisbt-plugins/source-integration/blob/bac190c62bee8d17c4768dd917f703af30d0dc40/Source/pages/checkin.php#L74), it seems this is a mandatory parameter that the plugin uses to determine which single "repository" in the source-integration configuration should process the updates. Our SVN repository currently contains a large number of projects, each of which contains the usual trunk/branches/tags folders. I had set up one source-integration "repository" for each of those projects within the shared repo, but there's only one hook script invocation point per SVN server-side repository, and SVN doesn't give the hook script any information about which paths within the repository were updated in the commit. That means the hook script can't easily tell which project name to supply when invoking the source-integration checkin API when you have multiple projects in the same repository. Should I just configure source-integration with one "repository" (and give up on distinguishing between trunk/branches/tags commits)? Or should I write a hook script which uses other SVN commands to identify which actual project is getting updated (or restructure our repository system)? I'm not sure what the impact will be if I don't have trunk/branches/tags paths enabled for the source-integration repo.

**Comment by DavidHopkinsFbr** [comment]
If it helps, I'll put together a PR that adds what I've learned to the documentation once I'm done setting up my system. I'll toss in some sample PowerShell scripts for calling the source-integration checkin hook on a Windows server, too.

**Comment by dregad** [comment]
> Are hook-driven notifications deprecated, or just undocumented?

Just undocumented. I switched to GIT many years ago and haven't used SVN since, so I lack technical knowledge and have little incentive to improve that.

With regards to your second question, I've never tested such configuration, but I believe both options would work - the plugin should still associate SVN revisions to the issue(s) referenced in the commit messages regardless of which actual repository it's stored in on the MantisBT side. I'm not sure what kind of side effect using multiple repos would have on the notion of parent commit.

> If it helps, I'll put together a PR that adds what I've learned to the documentation

That would be awesome ! :smiley:

**Comment by DavidHopkinsFbr** [comment]
Ok cool. I've got everything up and running and nicely integrated now. I'll raise a PR with some doco changes later this week, I hope.
