### ISSUE TITLE
SourceSVN hangs at stream_get_contents() ever since large svn commit.

### ISSUE THREAD

**Issue by seanm** [mantisbt-plugins/source-integration#314]
The SourceSVN plugin has been working great for us for many years. Recently, a coworker did a large svn commit (about 800 files, total 3.5 GB) and since then the plugin hasn't been working.

After some debugging, we determined that at [line 342](https://github.com/mantisbt-plugins/source-integration/blob/master/SourceSVN/SourceSVN.php#L342) this call to stream_get_contents() never returns:

```
$t_stderr = stream_get_contents( $t_pipes[2] );
```

Any advice how we can debug this further?

Perhaps there's a race condition where stream_get_contents() tries to read before there is anything ready?

Thanks.

**Comment by dregad** [comment]
@seanm sounds like you're facing the issue described in #261. Please confirm.

**Comment by seanm** [comment]
Thanks for the fast reply. It certainly sounds very similar. When back in the office tomorrow, I'll try some of things in #261. Thanks.

**Comment by seanm** [comment]
Yup, this is indeed a dupe of #261.

Swapping the two stream_get_contents() "fixed" the problem for both our test and production servers.

**Comment by dregad** [comment]
Thanks for your feedback.
