### ISSUE TITLE
Commit time not honouring user timezone

### ISSUE THREAD

**Issue by palevi67** [mantisbt-plugins/source-integration#317]
Using SourceSVN, commit times are always shown in UTC, while it makes sense to use user timezone configuration ...

![image](https://user-images.githubusercontent.com/3084095/61457886-92bc8780-a969-11e9-8f69-fbfd6bff6bf0.png)

**Comment by dregad** [comment]
This is confirmed also with GitHub changesets on mantisbt.org. Setting a different timezone in user prefs does not change the timestamp's display in source integration.

For example: commit mantisbt/mantisbt@a502d149a70a9043f1ac5206820c9370f53b73ad

Location | Timestamp | Source
 --- | --- | ---
Git CLI | 2019-08-09 00:27:24 +0200 | `git show a502d149a70a9043f1ac5206820c9370f53b73ad`
GitHub API | 2019-08-08T22:27:24Z | `curl https://api.github.com/repos/mantisbt/mantisbt/commits/a502d149a70a9043f1ac5206820c9370f53b73ad`
Source/view | 2019-08-08 18:27:24 | https://mantisbt.org/bugs/plugin.php?page=Source/view&id=24688

**Comment by dregad** [comment]
Sorry, I referenced the wrong issue in commit message.
