### ISSUE TITLE
Use Bitbucket Api 2.0

### ISSUE THREAD

**Issue by Xen3r0** [mantisbt-plugins/source-integration#320]
Any plan for integration of bitbucket api 2.0 ?

Actually, i can't import my latest changes because bitbucket remove some resources from their apis : https://developer.atlassian.com/cloud/bitbucket/deprecation-notice-v1-apis/

In my case, i have a error when the script try to get all branches.

**Comment by dregad** [comment]
I was not even aware that API 1.0 had been deprecated...

Bitbucket integration is community-maintained, so a pull request to adapt the plugin to the new version of the API would be welcome !

**Comment by Xen3r0** [comment]
PR : https://github.com/mantisbt-plugins/source-integration/pull/321

**Comment by dregad** [comment]
Many thanks for your contribution ! I just reviewed the PR.

**Comment by semanticfire** [comment]
Any timeframe to when the PR gets included ?

**Comment by dregad** [comment]
@semanticfire as mentioned in #321, I only did basic import tests. 

Did you check that the PR works as expected in other scenarios ? If so, it would be nice to have your feedback.

**Comment by semanticfire** [comment]
From the feedback on #321 I had the impression it was working as expected.
I'll have an opportunity to test full integration on Friday I'll not it down and comment on the PR

**Comment by semanticfire** [comment]
See https://github.com/mantisbt-plugins/source-integration/pull/321#issuecomment-528812186_

**Comment by dregad** [comment]
Release 2.3.0 is out. Thanks for your contribution !
