### ISSUE TITLE
Import not working on SourceSVN

### ISSUE THREAD

**Issue by realmofevil** [mantisbt-plugins/source-integration#323]
Hello,

We're migrating to the new MantisBT from a really old version 1.1.0 and the svnserve integration there was using the post-commit hook to send the svn log to the checkin.php. Then the commit log was posted as a comment to the bug page and that is what we need again.

The current MantisBT version we're trying to configure is 2.22.1 with source-integration 2.3.0.
Ubuntu 18.04; subversion 1.11.1; apache 2.4.39; php 7.3.8; MariaDB 10.4.6

When I press the button **Import Everything** or the **Import Latest Data** in _/plugin.php?page=Source/repo_manage_page_ (the Manage Repository page) and accept to do it - the page remains static and doesn't refresh or anything. I have waited a lot. Many times.

On the server, I saw that a shell command was being executed in the form of `svn --non-interactive --username '' --password '' log -v -r 0:HEAD --limit 200 svn://example.com/Repository/ --xml`.
I ran the same command from the terminal and outputted it to a log file, the resulting xml formatted file was looking fine. This action took no more than a second to execute successfully.

In the Configuration page, I have added `/usr/bin/` for the **SVN: Path to binary** field. _How should this work if the svnserve is not on localhost?_

**I think this might be the problem and I might have to add the API Key to some other config?** - I'm not sure what is the purpose of the **API Key**, either way I've generated a key with `openssl rand -hex 12` and added it to the field. _How should this work if the svnserve is not on localhost?_

**Allowed Addresses** are by default `localhost`, since the svnserve and Mantis are on the same server for the moment.

Our repositories are mostly non-standard, can the trunk, branches and tags fields be empty or what is the syntax to fill them? Relative paths from the root of the repo or absolute? I've even tried with just a slash `/`.

After every time I tried to make an import, I had to restart the Apache because Mantis becomes unresponsive. At the end just an empty import appears, whatever that is, I don't know. See attached image. The **Blank** project is the repository that I made, the other one appears after the server restart.
![image](https://user-images.githubusercontent.com/38146393/64859767-ccd99b00-d633-11e9-8123-cd38a2ec746d.png)

Also, should the tools directory be put inside the plugins, together with Source and SourceSVN?

**Comment by realmofevil** [comment]
Okay, problem solved.
The API Key has to be in the post-commit hook, used the added template to test it and everything seems to be working.

**Comment by dregad** [comment]
Hello,

Glad to hear you solved your problem. I don't use SVN myself so I would have been hard pressed to help.

About the "import XXXX" repository - when you do a full import, a new, temporary repo is created (with the timestamp in the name), then all the changesets are imported into it; when this is completed, the old repo is deleted and the temp one renamed. You're seeing this because something went wrong and the process did not finish.

There are known issues with full import process, particularly with large repositories.

#259 might be of interest to you as well.

**Comment by realmofevil** [comment]
Thanks for the response, it failed because I had not added the API key to the post-commit hook, this wasn't explained in any docs and it is obvious but I forgot about it, since I was following the steps from the docs to configure the plugin.

**Comment by dregad** [comment]
It would be great if you could send a PR with improved documentation !
