### ISSUE TITLE
[Bug - GitHub] Invalid import address URL

### ISSUE THREAD

**Issue by redstonedesigner** [mantisbt-plugins/source-integration#324]
http://mantis.[SITE].com/plugin.php?page=Source/import&id=all&api_key=[KEY]"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    29  100    29    0     0   2900      0 --:--:-- --:--:-- --:--:--  2900
Invalid remote import address

**Comment by redstonedesigner** [comment]
No data is imported, by the way.

**Comment by dregad** [comment]
I'm closing this, as it works just fine for me. Feel free to reopen with detailed instructions to reproduce the error.
