### ISSUE TITLE
Can't import from a Bitbucket team repository

### ISSUE THREAD

**Issue by simaoj** [mantisbt-plugins/source-integration#325]
Can't import information from a repository on a bitbucket team. I don't get either data or error message. Tried with GitHub and GitLab repositories, and it works like a charm.

**Comment by distante** [comment]
Did you got any info about this? I have the exact same problem.

**Comment by simaoj** [comment]
Nope. I couldn't get it to work, so I just gave up for the time being...

**Comment by dregad** [comment]
Closing this as there is not enough information provided to provide any help.
