### ISSUE TITLE
Cannot install Source plugin on Mantisbt 2.22.1

### ISSUE THREAD

**Issue by dcorrigangoempyrean** [mantisbt-plugins/source-integration#326]
This happens when I copy over the Source/ directory to my plugins directory.
Fresh upgrade of 2.22.1 from 1.2.20
Ubuntu 16.04
Apache 2.4
PHP 7.0

APPLICATION ERROR #26

Data Type mismatch. Enable detailed error messages for further information.

Please use the "Back" button in your web browser to return to the previous page. There you can correct whatever problems were identified in this error or select another action. You can also click an option from the menu bar to go directly to a new section.

Detailed error information
Full path: /var/www/mantisbt-2.22.1/core/helper_api.php
Line number: 191

\# | Filename | Line | Class | Type | Function | Args
-- | -- | -- | -- | -- | -- | --
0 | /var/www/mantisbt-2.22.1/core/helper_api.php | 191 | - | - | trigger_error | <string>'26', <integer>256
1 | /var/www/mantisbt-2.22.1/core/helper_api.php | 268 | - | - | helper_check_variables_equal | <NULL>NULL, <integer>5, <boolean>true
2 | /var/www/mantisbt-2.22.1/core/print_api.php | 1260 | - | - | check_selected | <NULL>NULL, <integer>5
3 | /var/www/mantisbt-2.22.1/manage_plugin_page.php | 190 | - | - | print_plugin_priority_list | <NULL>NULL

**Comment by dregad** [comment]
Can you check the contents of the *mantis_plugins_table*, are there any NULL values in the _priority_ column ?

There should not be any; if there are, you should replace them by `3`.
