### ISSUE TITLE
Input field for "GitLab API Key" should have "type=password"

### ISSUE THREAD

**Issue by CamilleDesmots** [mantisbt-plugins/source-integration#329]
In the function "update_repo_forl" of the file "[SourceGitlab.php](https://github.com/mantisbt-plugins/source-integration/blob/master/SourceGitlab/SourceGitlab.php)" the input field for "GitLab API key" should have the attribute "type=password".
See the text in bold in this sample : 
```<tr>
<td class="category"><?php echo plugin_lang_get( 'hub_app_secret' ) ?></td>
<td>
```
<input type="text" name="hub_app_secret" **type=password** maxlength="250" size="40" value="<?php echo string_attribute( $t_hub_app_secret ) ?>"/>
```
</td>
</tr>
```

**Comment by messeant** [comment]
Thé password of SVN top.
