### ISSUE TITLE
GitLab integration has several drawbacks (e.g. no files in the changesets)

### ISSUE THREAD

**Issue by being-peace** [mantisbt-plugins/source-integration#343]
Here is a pull request that improves the GitLab integration in several ways, see https://github.com/mantisbt-plugins/source-integration/pull/342

(Sorry, I don't know if it is appropriate to submit an issue and a pull request.)

**Comment by dregad** [comment]
> I don't know if it is appropriate to submit an issue and a pull request

In this specific case it's really not necessary as the Issue is not providing any additional information compared to the PR.
