### ISSUE TITLE
gitlab push webhook: Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by rattkin** [mantisbt-plugins/source-integration#346]
I set up webhooks by following this guide:
https://github.com/mantisbt-plugins/source-integration/blob/master/SourceGitlab/README.md

When I test the webhook in gitlab, I get HTTP 200 response, but in the body, there is a 

SYSTEM WARNING
'count(): Parameter must be an array or an object that implements Countable' in '/srv/www/htdocs/mantis/plugins/SourceGitlab/SourceGitlab.php' line 367

**Comment by dregad** [comment]
Confirmed
