### ISSUE TITLE
Unable to access Repositories Page - DB Error

### ISSUE THREAD

**Issue by TheMeanMachine** [mantisbt-plugins/source-integration#349]
The following error occurs when I access the repositories page (http://mantis.test/mantis/plugin.php?page=Source/index)

Seemingly no tables have been created by the plugin. This is all on a fresh install of the latest Mantis.

APPLICATION ERROR #401

Database query failed. Error received from database was #1146: Table 'mantis_new.mantis_plugin_Source_repository_table' doesn't exist for the query: SELECT * FROM mantis_plugin_Source_repository_table ORDER BY name ASC.
Please use the "Back" button in your web browser to return to the previous page. There you can correct whatever problems were identified in this error or select another action. You can also click an option from the menu bar to go directly to a new section.

**Comment by dregad** [comment]
I'm not able to reproduce this. The tables should be created when you install the plugin via http://mantis.test/mantis/manage_plugin_page.php. 

Does your DB user have the privileges to create tables/indexes ?
How did you install the plugin ? Were there any errors at install time ?

**Comment by TheMeanMachine** [comment]
It's the same user which created the initial tables.
Installed via the manage plugins page you cited & I got no errors. I'm a little baffled.

**Comment by TheMeanMachine** [comment]
This fixed it: https://stackoverflow.com/a/15408615

**Comment by dregad** [comment]
Thanks for the feedback, and glad to hear you managed to fix the problem.

> This fixed it: https://stackoverflow.com/a/15408615

This begs the question: how was MantisBT - and more specifically the database - installed initially ? In other words, how could you have a schema version set for the Source plugin in your config, but no corresponding tables ? This most likely involved direct database manipulation at some point (e.g. dropping the schema tables).
