### ISSUE TITLE
Schema errors on install

### ISSUE THREAD

**Issue by TheEvilCoder42** [mantisbt-plugins/source-integration#360]
* MariaDB: 10.3.14
* MantisBT: 2.24.4
* Release: 2.4.1

Using the following Docker Compose Stack (which uses mysql, but gives the same error): https://github.com/okainov/mantisbt-docker

When trying to install the plugin I get the following error:

```
APPLICATION ERROR #2503

Upgrading the plugin schema failed at step #6. Error "Table 'bugtracker.mantis_plugin_source_file_table' doesn't exist" occurred while executing the following statement(s):
ALTER TABLE mantis_plugin_Source_file_table ADD action VARCHAR(8) NOT NULL DEFAULT ''

Please use the "Back" button in your web browser to return to the previous page. There you can correct whatever problems were identified in this error or select another action. You can also click an option from the menu bar to go directly to a new section.
```

It looks like there are errors in the plugin_source table schemas, since at least this table seems corrupt.

I get the same error when trying to upgrade the version.

The user has full privileges (not as in issue #181).

The Table suffix is default and the tables look good (apart from the corruption) (not as in issue #212);
```
MariaDB [bugtracker2]> SHOW TABLES;
+---------------------------------------+
| Tables_in_bugtracker2                 |
+---------------------------------------+
| mantis_api_token_table                |
| mantis_bug_file_table                 |
| mantis_bug_history_table              |
| mantis_bug_monitor_table              |
| mantis_bug_relationship_table         |
| mantis_bug_revision_table             |
| mantis_bug_table                      |
| mantis_bug_tag_table                  |
| mantis_bug_text_table                 |
| mantis_bugnote_table                  |
| mantis_bugnote_text_table             |
| mantis_category_table                 |
| mantis_config_table                   |
| mantis_custom_field_project_table     |
| mantis_custom_field_string_table      |
| mantis_custom_field_table             |
| mantis_email_table                    |
| mantis_filters_table                  |
| mantis_news_table                     |
| mantis_plugin_Source_bug_table        |
| mantis_plugin_Source_changeset_table  |
| mantis_plugin_Source_file_table       |
| mantis_plugin_Source_repository_table |
| mantis_plugin_table                   |
| mantis_project_file_table             |
| mantis_project_hierarchy_table        |
| mantis_project_table                  |
| mantis_project_user_list_table        |
| mantis_project_version_table          |
| mantis_sponsorship_table              |
| mantis_tag_table                      |
| mantis_tokens_table                   |
| mantis_user_pref_table                |
| mantis_user_print_pref_table          |
| mantis_user_profile_table             |
| mantis_user_table                     |
+---------------------------------------+
36 rows in set (0.001 sec)
```

Issue #312 & #359 didn't helped either.

Thanks for your help.

**Comment by dregad** [comment]
I am not able to reproduce this with a fresh install of MantisBT. It is most likely caused by something specific to your docker setup, but I don't have the time to try and replicate the problem in this context.

Plugin schema upgrade is failing at [step 6](https://github.com/mantisbt-plugins/source-integration/blob/master/Source/Source.php#L249), stating that `mantis_plugin_Source_file_table` does not exist. 

This table is normally created at [step 3](https://github.com/mantisbt-plugins/source-integration/blob/master/Source/Source.php#L236), and per your report the table is there, so please check if there were any prior errors in the installation process. What does the table look like (describe) ?

Also, what do you get from `select * from mantis_config_table where config_id like 'plugin_Source%';` ?

**Comment by dregad** [comment]
OK so just I gave the docker image a spin and the Source Integration plugin installed flawlessly, so I guess the problem is with your specific setup.

**Comment by TheEvilCoder42** [comment]
I tested this on a Macbook Pro, seems this was the culprit, I have no issues on a Debian server..

I'll try again on thursday on my Macbook Pro and will keep you updated on further findings.
