### ISSUE TITLE
VisualSVN 4.3.3 x64 + mantis2.25.0 + source-integration-2.4.1

### ISSUE THREAD

**Issue by sercherep** [mantisbt-plugins/source-integration#363]
Good day!

set up according to the instructions ..

Name repo
Type VisualSVN Server
URL http://x.x.x.x/!/#repo
user=xx
password=xx

x.x.x.x = my ip
http://x.x.x.x/!/#repo = open in browser ok!

when I click the "import recent changes" button, I see an error: 

(in mantis config set $g_show_detailed_errors = ON)

APPLICATION ERROR #plugin_SourceVisualSVNServer_svn_cmd
Subversion execution returned an error: "sh: 1: svn: not found".
Full path: /core/plugin_api.php
Line number: 449
Stack trace
0 /core/plugin_api.php	449	-	-	trigger_error	<string>'plugin_SourceVisualSVNServer_svn_cmd', <integer>256
1 /plugins/SourceSVN/SourceSVN.php  361  -  -  plugin_error  <string>'svn_cmd'
2 /plugins/SourceSVN/SourceSVN.php  285 SourceSVNPlugin  ->  svn_run  <string>'...
..

please tell me what to do
thanks!

**Comment by dregad** [comment]
Did you configure the plugin's `SVN: Path to binary` setting ?

**Comment by dregad** [comment]
Closing due to lack of feedback. Feel free to reopen if needed.
