### ISSUE TITLE
checkin.php should not return HTTP/200 when operation fails

### ISSUE THREAD

**Issue by dregad** [mantisbt-plugins/source-integration#365]
Currently, when given an invalid payload, checkin.php informs caller about failure by displaying a standard MantisBT error page.

This is not easily processed in automated scenarios (e.g. webhooks), which are the normal usage of this page.

Page should return an appropriate HTTP 4xx error code in this case.

**Comment by obmsch** [comment]
@dregad It's not just the payload, but any error/exception in the current source plugin (#266). For me it's most
likely a windows (feature) update silently breaking my environment (SVN). I worked around it, by checking the
response (page) for any errors, in my post-commit hook.
