### ISSUE TITLE
Github deprecating API authentication through query parameters

### ISSUE THREAD

**Issue by teodortalov** [mantisbt-plugins/source-integration#368]
Github authentication no longer working. Docs state that the cut off date is Sept 8, 2021, but authentication has stop working. 

https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/

![Screen Shot 2021-05-05 at 2 03 19 PM](https://user-images.githubusercontent.com/2781820/117188256-dd133080-adaa-11eb-8fcf-494262c3bcf7.png)

**Comment by dregad** [comment]
> Docs state that the cut off date is Sept 8, 2021, but authentication has stop working

From the very link you provided:

<i>Brownouts

During a brownout, authentication using query parameters will temporarily fail. The goal is to trigger alerts (assuming there are any) on our customers' services to help them find unmigrated authentication calls.

The brownouts are scheduled for:
- **May 5, 2021: For 12 hours starting at 14:00 UTC**
- June 9, 2021: For 24 hours starting at 14:00 UTC
- August 11, 2021: For 48 hours starting at 14:00 UTC
</i>

That being said, unless I missed something, this issue has already been addressed nearly 1 year ago in [release 2.4.0](https://github.com/mantisbt-plugins/source-integration/releases/tag/v2.4.0), see #335.
