### ISSUE TITLE
Gitlab integration: 'Diff' button generates incorrect URL (mantis & gitlab domains concatenated)

### ISSUE THREAD

**Issue by seanm** [mantisbt-plugins/source-integration#371]
Not sure if I've configured something wrong, or it's a bug, but the 'Diff' button in every changeset has a URL of this form:

`https://mantis.example.com/bugs/gitlab.example.com/namespace/project/commit/SHA`

when it should be:

`https://gitlab.example.com/namespace/project/commit/SHA`

Note how the mantis URL (`https://mantis.example.com/bugs/`) is prepended.

I've looked through the docs and settings, but I don't see anything that explains this... so perhaps it's a bug...

**Comment by dregad** [comment]
It works just fine for me
![image](https://user-images.githubusercontent.com/449891/118105005-25020b00-b3dc-11eb-86da-977cbbe80c79.png)

So it's probably something in the way you configured your repo... 

Depending on context, this URL is built in one of the [SourceGitlab::url_xxx() methods](https://github.com/mantisbt-plugins/source-integration/blob/v2.4.1/SourceGitlab/SourceGitlab.php#L67), by concatenating _hub_root_ and _hub_reponame_ settings, so check what you have for those.

**Comment by seanm** [comment]
Hi @dregad thanks for your response. 

I've poked through the code to try and be sure which variable name corresponds to what in the UI, but I'm not sure. Is this the case:

`hub_root` -> "GitLab Root"
`hub_reponame` -> "GitLab Repository Name"

In my settings (at `plugin.php?page=Source/repo_manage_page`) I have:

"URL": blank
"GitLab Root": `gitlab.example.com`
"GitLab Repository Name": `namespace/project`

**Comment by dregad** [comment]
> GitLab Root": `gitlab.example.com`

If that is indeed the exact value you have in this field, then this is your problem right there.

The plugin builds the Diff button's target as `"$t_root/$t_reponame/commit/$t_ref"`, so in your case, `gitlab.example.com/namespace/project/commit/SHA`. This is a relative URL, so it is appended to your MantisBT root.

As mentioned on the _repo_update_page_, the plugin expects a **full URL** to your Gitlab instance, not just a hostname (i.e. including the protocol). You should probably have `https://gitlab.example.com` here.

**Comment by seanm** [comment]
>If that is indeed the exact value you have in this field, then this is your problem right there.

Indeed that was it. Thanks!

>As mentioned on the repo_update_page, the plugin expects a full URL to your Gitlab instance

So it does. Guess I read too fast.

Thanks for #373 !

**Comment by seanm** [comment]
@dregad do you know of any public projects using mantis with gitlab integration?  We might be seeing some mixup of commits and branches and tickets, and it would be handy to look how it's working elsewhere....
