### ISSUE TITLE
source-integration error

### ISSUE THREAD

**Issue by abbasymusbbar** [mantisbt-plugins/source-integration#378]
Hello 
When I try to install plugins SourceBitBucket from source-integration-2.4.1 its give me error "..../plugins/SourceBitBucket/SourceBitBucket.php' line 6"

Can you please check this.

I have installed mantisBT 2.25.2 in
Ubuntu 20.04
PHP 7.4
MySQL 8.0.27

**Comment by dregad** [comment]
I am not able to reproduce this, the plugins installs just fine. 
You did not specify the actual error so without additional information there's nothing more I can do at this time.
