### ISSUE TITLE
Mapping SVN repos with Mantis projects

### ISSUE THREAD

**Issue by thabsheerpk** [mantisbt-plugins/source-integration#393]
Hi team,
Recently we added source integration plugin with mantis for integrating our SVN projects with mantis tickets. But we facing a confidentiality issue, like once we created repositories, those will be available to all types of users in mantis. 

@vboctor @giallu @daryn @rombert 
I would like know "how to do the mapping of SVN project name ( change sets ) with Mantis project to ensure that a user from a project 1 in mantis can access only project 1's SVN repo"

**Comment by dregad** [comment]
Assuming my understanding is correct, what you are asking is unfortunately not feasible currently with the Source Integration plugin.

Please see #49 for the existing feature request. Contributions are welcome.

I'm going to close this as duplicate, feel free to reopen if this is incorrect.
