### ISSUE TITLE
No install button for the plugin

### ISSUE THREAD

**Issue by PranatoshRoy** [mantisbt-plugins/source-integration#404]
![image](https://user-images.githubusercontent.com/15941384/203932980-171e4aae-59c6-4bb0-a283-c7b888e42615.png)

**Comment by dregad** [comment]
As shown on your screenshot, the Source Integration plugin requires *MantisBT 2.24.0*. 

The dependency is displayed in brown, meaning it is outdated, in other words you are running an older version of MantisBT. The *Install* button will be displayed when dependencies are met.
