### ISSUE TITLE
Uploading mantis issues into gitlab

### ISSUE THREAD

**Issue by bpabla50** [mantisbt-plugins/source-integration#405]
Hi :
We have mantis 1.2.17 with postgresql 10.2 running on our site. I have exported all the issues for a project into  CSV file. This CSV file does not include "Notes" for a given issue. I went into mantis GUI, and saw "notes" does not show in "ALL available  columns", hence "CSV columns" does not have "notes". Is someone can suggest, how to include "notes" in exported CSV file from mantis.
I am using this tool to read info from this CSV file, and uploading to gitlab: https://gitlab.kitware.com/utils/mantis-to-gitlab. This tool works fine, but needs some improvement.
Thanks for any help.

**Comment by dregad** [comment]
This is the source integration plugin, which has nothing to do with exporting issues from Mantis.

I don't quite understand why you're coming here asking for support on a 3rd-party tool... It would be better to seek assistance from the guys who developed it, no ?

If you need some help with Mantis, I suggest you post on the [community forums](https://mantisbt.org/forums).

**Comment by bpabla50** [comment]
Thanks. Sorry for posting here as I was not sure. I saw a few issues with mantisbt here.
