### ISSUE TITLE
no Authorize button

### ISSUE THREAD

**Issue by kainnon** [mantisbt-plugins/source-integration#410]
Hello,

I don't have any "Authorize" button when I configure GitHub repo

Mantis version 2.26.0

Thanks for your help!

**Comment by dregad** [comment]
The *Authorize* button is shown once the *Client ID* and *Secret* have been recorded in the repository's configuration, as explained in [the documentation](https://github.com/mantisbt-plugins/source-integration/blob/4036ad18ee47b33a77ccc93bb08852ea5a5440db/docs/CONFIGURING.SourceGithub.md).
