### ISSUE TITLE
Anonymous user can view changesets page

### ISSUE THREAD

**Issue by fredfox1** [mantisbt-plugins/source-integration#414]
Please contact me for details

**Comment by dregad** [comment]
> Please contact me for details

... How ?

**Comment by dregad** [comment]
Anyway, did you try setting the *View Threshold* to something higher than *Viewer* ?

![image](https://github.com/mantisbt-plugins/source-integration/assets/449891/f5e47484-a178-4ad2-a447-4c5ce63c3c4d)

**Comment by fredfox1** [comment]
Thank you for responding. That was the configuration setting I was missing and it solved the issue. The deep link no longer allows anonymous to view the changesets page. Seems that I did not understand "view thresholds" very well. The security scanners were using fuzzing to test our site. Amazing what they can find.

I am very grateful for your time.

Fred Fox, IT Applications Specialist, PhD
USDA-ARS Rangeland Resources and Systems Research Unit
2150 Centre Avenue, Bldg. D. Suite 200
Fort Collins, CO 80526
Phone: 970-492-7321
Email: ***@***.***

________________________________
