### ISSUE TITLE
Possible leak of GH token

### ISSUE THREAD

**Issue by jrcii** [mantisbt-plugins/source-integration#415]
Our team will be researching further, but as an early PSA: a private GH token which was exclusively provided to this plugin was found by GitHub to be publicly available.

This was provided to Mantis on a server where all OS packages were up to date and SSH keys only.

We will be conducting a preliminary security audit on this plugin and Mantis and report back any findings. Normally I would wait to mention this until conclusive data was available but this is so potentially catastrophic I thought it best users are on alert.

**Comment by dregad** [comment]
Thanks for the report, let me know the results of your analysis.

**Comment by jrcii** [comment]
This leak was caused by an insecure Apache configuration and not due to any vulnerability found in the source of the plugin.

**Comment by dregad** [comment]
Thanks for the feedback 😅
