### ISSUE TITLE
Assign Mantis project to Source Integration repository

### ISSUE THREAD

**Issue by Dimas-sc** [mantisbt-plugins/source-integration#417]
I have the Source Control Integration plugin, compatible with Subversion (WebSVN) and GIT (Gitea). I have different repositories configured, some with SVN and others with GIT. The problem is that the issue IDs may overlap. That is, issue #123 may exist in a Subversion repository but also in a GIT repository. And if I make a commit closing issue #123, it may close it in both repositories. How can I prevent this from happening? Can I assign a MantisBT project to a specific repository?

**Comment by Dimas-sc** [comment]
Ok, so the problem is that when I import the new repository from Gitea, is it possible that they load all the history of commits?

We are migrating from Gitea issues to Mantis, and there are Gitea issues ID that overlaps with some Mantis issues. And when I create the Gitea repository, the system starts to close and "edit" past Mantis issues. Is it possible to avoid that and don't import history movements?

**Comment by dregad** [comment]
Ah, I think see what you mean now. Your commit messages in the Gitea repository are referencing Gitea issues, the numbering of which does not match the MantisBT issue Ids. 

So when the Source Integration processes the old commits, the wrong issues are referenced and updated.

Indeed when importing a repository all the changeset's commit messages are parsed. Issues mapping and resolution is controlled by the regex in the plugin's configuration (_Issues references RegEx_ / _Resolved Issues references RegEx_) so you could temporarily change these settings to something that will not match, and restore the value after import.

**Comment by Dimas-sc** [comment]
Exactly! I meant to say this, I'm sorry, I explained myself poorly. Well, we'll do it this way, thank you very much 👌
