### ISSUE TITLE
Installation instructions are not clear

### ISSUE THREAD

**Issue by cppexpert** [mantisbt-plugins/source-integration#67]
Hey guys,

I'm not sure I understand what parameters to set in `Update Repository` view on Mantis. 

What exactly should I specify in `GitHub Application Client ID` ?
Should I create new OAuth app in https://github.com/settings/applications ?
If yes, what call back url I'm supposed to specify ?

Thanks.

**Comment by morgant** [comment]
I've _finally_ submitted Pull Request #131 which adds the documentation laid out in this issue.

**Comment by luzpaz** [comment]
Thanks!
