### ISSUE TITLE
XML Getting truncated

### ISSUE THREAD

**Issue by pdugas** [mantisbt-plugins/source-integration#88]
```
$t_svnlog_xml = shell_exec( "$svn log -v -r $t_rev:HEAD --limit 200 $t_url --xml" );
```

Not sure why but after that line in SourceSVN.php is run, $t_svnlog_xml is missing the last &lt;/log&gt; tag and the call to process_svn_log_xml() fails.  I hacked around it with $t_svnlog_xml.='&lt;/log&gt;'.  When I run the SVN command manually, the trailing </log> tag is there.  Weird.

**Comment by dregad** [comment]
I am not able to reproduce this. The XML output includes the closing `</log>`.
